#pragma once
namespace nest
{
    enum class Keycodes // matches SDL scancodes perfectly 
    {                   // (if adding other middlewares, will need to make conversion functions)
        Key_Nothing,
        Key_A = 4,
        Key_B,
        Key_C,
        Key_D,
        Key_E,
        Key_F,
        Key_G,
        Key_H,
        Key_I,
        Key_J,
        Key_K,
        Key_L,
        Key_M,
        Key_N,
        Key_O,
        Key_P,
        Key_Q,
        Key_R,
        Key_S,
        Key_T,
        Key_U,
        Key_V,
        Key_W,
        Key_X,
        Key_Y,
        Key_Z,

        Key_1,
        Key_2,
        Key_3,
        Key_4,
        Key_5,
        Key_6,
        Key_7,
        Key_8,
        Key_9,
        Key_0,

        Key_Return,
        Key_Escape,
        Key_Backspace,
        Key_Tab,
        Key_Space,

        Key_Minus,
        Key_Equals,
        Key_LeftBracket,
        Key_RightBracket,
        Key_Backslash,
        Key_Comma = 54,
        Key_Period,
        Key_Slash,
        Key_CapsLock,

        Key_F1,
        Key_F2,
        Key_F3,
        Key_F4,
        Key_F5,
        Key_F6,
        Key_F7,
        Key_F8,
        Key_F9,
        Key_F10,
        Key_F11,
        Key_F12,

        Key_PrintScreen,
        Key_ScrollLock,
        Key_Pause,
        Key_Insert,

        Key_Home,
        Key_PageUp,
        Key_Delete,
        Key_End,
        Key_PageDown,

        Key_RightArrow,
        Key_LeftArrow,
        Key_DownArrow,
        Key_UpArrow,

        Key_NumpadDivide = 84,
        Key_NumpadMultiply,
        Key_NumpadSubtract,
        Key_NumpadAdd,
        Key_NumpadEnter,
        Key_Numpad1,
        Key_Numpad2,
        Key_Numpad3,
        Key_Numpad4,
        Key_Numpad5,
        Key_Numpad6,
        Key_Numpad7,
        Key_Numpad8,
        Key_Numpad9,
        Key_Numpad0,
        Key_NumpadDecimal,

        Key_LeftCtrl = 224,
        Key_LeftShift,
        Key_LeftAlt,

        Key_RightCtrl = 228,
        Key_RightShift,
        Key_RightAlt,
        Key_WindowClose,

        // these don't match SDL and are unique to the engine
        Key_LeftMouse,
        Key_RightMouse,
        Key_MiddleMouse,
        Key_Mouse1, // side button
        Key_Mouse2 // side button
    };

    static constexpr Keycodes m_kKeys[] = 
    {
        Keycodes::Key_Nothing,
        Keycodes::Key_A,
        Keycodes::Key_B,
        Keycodes::Key_C,
        Keycodes::Key_D,
        Keycodes::Key_E,
        Keycodes::Key_F,
        Keycodes::Key_G,
        Keycodes::Key_H,
        Keycodes::Key_I,
        Keycodes::Key_J,
        Keycodes::Key_K,
        Keycodes::Key_L,
        Keycodes::Key_M,
        Keycodes::Key_N,
        Keycodes::Key_O,
        Keycodes::Key_P,
        Keycodes::Key_Q,
        Keycodes::Key_R,
        Keycodes::Key_S,
        Keycodes::Key_T,
        Keycodes::Key_U,
        Keycodes::Key_V,
        Keycodes::Key_W,
        Keycodes::Key_X,
        Keycodes::Key_Y,
        Keycodes::Key_Z,
        Keycodes::Key_1,
        Keycodes::Key_2,
        Keycodes::Key_3,
        Keycodes::Key_4,
        Keycodes::Key_5,
        Keycodes::Key_6,
        Keycodes::Key_7,
        Keycodes::Key_8,
        Keycodes::Key_9,
        Keycodes::Key_0,
        Keycodes::Key_Return,
        Keycodes::Key_Escape,
        Keycodes::Key_Backspace,
        Keycodes::Key_Tab,
        Keycodes::Key_Space,
        Keycodes::Key_Minus,
        Keycodes::Key_Equals,
        Keycodes::Key_LeftBracket,
        Keycodes::Key_RightBracket,
        Keycodes::Key_Backslash,
        Keycodes::Key_Comma,
        Keycodes::Key_Period,
        Keycodes::Key_Slash,
        Keycodes::Key_CapsLock,
        Keycodes::Key_F1,
        Keycodes::Key_F2,
        Keycodes::Key_F3,
        Keycodes::Key_F4,
        Keycodes::Key_F5,
        Keycodes::Key_F6,
        Keycodes::Key_F7,
        Keycodes::Key_F8,
        Keycodes::Key_F9,
        Keycodes::Key_F10,
        Keycodes::Key_F11,
        Keycodes::Key_F12,
        Keycodes::Key_PrintScreen,
        Keycodes::Key_ScrollLock,
        Keycodes::Key_Pause,
        Keycodes::Key_Insert,
        Keycodes::Key_Home,
        Keycodes::Key_PageUp,
        Keycodes::Key_Delete,
        Keycodes::Key_End,
        Keycodes::Key_PageDown,
        Keycodes::Key_RightArrow,
        Keycodes::Key_LeftArrow,
        Keycodes::Key_DownArrow,
        Keycodes::Key_UpArrow,
        Keycodes::Key_NumpadDivide,
        Keycodes::Key_NumpadMultiply,
        Keycodes::Key_NumpadSubtract,
        Keycodes::Key_NumpadAdd,
        Keycodes::Key_NumpadEnter,
        Keycodes::Key_Numpad1,
        Keycodes::Key_Numpad2,
        Keycodes::Key_Numpad3,
        Keycodes::Key_Numpad4,
        Keycodes::Key_Numpad5,
        Keycodes::Key_Numpad6,
        Keycodes::Key_Numpad7,
        Keycodes::Key_Numpad8,
        Keycodes::Key_Numpad9,
        Keycodes::Key_Numpad0,
        Keycodes::Key_NumpadDecimal,
        Keycodes::Key_LeftCtrl,
        Keycodes::Key_LeftShift,
        Keycodes::Key_LeftAlt,
        Keycodes::Key_RightCtrl,
        Keycodes::Key_RightShift,
        Keycodes::Key_RightAlt,
        Keycodes::Key_LeftMouse,
        Keycodes::Key_RightMouse,
        Keycodes::Key_MiddleMouse,
        Keycodes::Key_Mouse1,
        Keycodes::Key_Mouse2
    };
};